### ISSUE TITLE
testcontainers/ryuk from private registry

### ISSUE THREAD

**Issue by imvs** [xvik/gradle-use-python-plugin#141]
**Error:**
```
Execution failed for task ':checkPython'.
> Can't get Docker image: RemoteDockerImage(imageName=testcontainers/ryuk:0.6.0, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@5cd6ca23)
  	 Failed to pull image: testcontainers/ryuk:0.6.0
  		 Status 500: {"message":"Get \"https://registry-1.docker.io/v2/\": net/http: TLS handshake timeout"}
```

**Question:**
Is there any possibility to set custom ryuk image?

**Comment by xvik** [comment]
Doc about [private registries](https://java.testcontainers.org/features/image_name_substitution/#automatically-modifying-docker-hub-image-names).

Probably, this is what you need

```groovy
python.environment 'TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX', 'registry.mycompany.com/mirror/'
```

(or just put full image page (from private repo) in TESTCONTAINERS_RYUK_CONTAINER_IMAGE)

**Comment by imvs** [comment]
Many thanks! 
```
hub.image.name.prefix=registry.mycompany.com/mirror/
```
or
```
ryuk.container.image=privat.registry/testcontainers/ryuk\:0.3.3
```

in ```~/.testcontainers.properties``` works!

**Comment by xvik** [comment]
Thank you for info! [Documentation updated](https://xvik.github.io/gradle-use-python-plugin/latest/guide/docker/#testcontainers-configuration)
