### ISSUE TITLE
Support pip install from git+https, et al.

### ISSUE THREAD

**Issue by kruton** [xvik/gradle-use-python-plugin#2]
I have some packages that have not released a version on PyPI, but I want to compile against a specific git commitish. Unfortunately, the pip syntax only allows `name:version` and not all the `git+...` combinations.

You should be able to have a `requirements.txt` that looks like:
```
foo==1.1.2
git+git://github.com/kruton/awesome-python-repo@f00ba5#egg=bar
baz==9.4.2
```

**Comment by xvik** [comment]
Added support for "extended" format: vcs+protocol://repo_url/@vcsVersion#egg=pkg-pkgVersion.

For example: `python.pip 'git+git://github.com/kruton/awesome-python-repo@f00ba5#egg=bar-1.0'`

Two versions are required:
* vcs version for reproducible builds (@vcsVersion); but tag or branch name still could be specified
* package version (-pkgVersion) is required to perform up to date checks in gradle (without running pip)

In spite of the fact, that `#egg=name-version` is official convention it is not working (at least for me) so i cut off version part and use raw `git+git://github.com/kruton/awesome-python-repo@f00ba5#egg=bar` for actual installation.

It should be possible to use [any supported vcs](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support).

Please tell me if you see any potential issues.

I'm going to release new version tomorrow (if I have time to update docs)
