### ISSUE TITLE
Could not find method register() for arguments

### ISSUE THREAD

**Issue by amanjain08** [xvik/gradle-use-python-plugin#20]
Not able to install the plugin after adding the plugin dependency.

When I am loading the gradle changes, gradle is failing with an error

`

> An exception occurred applying plugin request [id: 'ru.vyarus.use-python', version: '2.2.0']
> > Failed to apply plugin [id 'ru.vyarus.use-python']
>    > Could not find method register() for arguments [checkPython, class ru.vyarus.gradle.plugin.python.task.CheckPythonTask, ru.vyarus.gradle.plugin.python.PythonPlugin$_apply_closure2@2039cab8] on task set of type org.gradle.api.internal.tasks.DefaultTaskContainer.

`

**Gradle Debug Logs**

`12:17:00.082 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'gradle-use-python-plugin.jar (ru.vyarus:gradle-use-python-plugin:2.3.0)' in resolver cache: .gradle/caches/modules-2/files-2.1/ru.vyarus/gradle-use-python-plugin/2.3.0/fc5c63e2cf1652fb99e00cd0159b41f6dc6c998f/gradle-use-python-plugin-2.3.0.jar
12:17:00.082 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'snakeyaml.jar (org.yaml:snakeyaml:1.17)' in resolver cache: .gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/1.17/7a27ea250c5130b2922b86dea63cbb1cc10a660c/snakeyaml-1.17.jar
12:17:00.083 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve gradle-properties-plugin.jar (net.saliman:gradle-properties-plugin:1.4.6)' completed
12:17:00.083 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Resolve gradle-use-python-plugin.jar (ru.vyarus:gradle-use-python-plugin:2.3.0)'
12:17:00.083 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.2.3 completed (2 worker(s) in use)
12:17:00.083 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Resolve snakeyaml.jar (org.yaml:snakeyaml:1.17)'
12:17:00.084 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 10: released lock on root.1.2.3
12:17:00.085 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Resolve files of :classpath'
12:17:00.086 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve files of :classpath' completed
12:17:00.086 [DEBUG] [org.gradle.internal.component.model.ComponentAttributeMatcher] Selected match net.saliman:gradle-properties-plugin:1.4.6 configuration default from candidates [net.saliman:gradle-properties-plugin:1.4.6 configuration default] for {}
12:17:00.086 [DEBUG] [org.gradle.internal.component.model.ComponentAttributeMatcher] Selected match org.yaml:snakeyaml:1.17 configuration default from candidates [org.yaml:snakeyaml:1.17 configuration default] for {}
12:17:00.086 [DEBUG] [org.gradle.internal.component.model.ComponentAttributeMatcher] Selected match ru.vyarus.use-python:ru.vyarus.use-python.gradle.plugin:2.3.0 configuration default from candidates [ru.vyarus.use-python:ru.vyarus.use-python.gradle.plugin:2.3.0 configuration default] for {}
12:17:00.087 [DEBUG] [org.gradle.internal.component.model.ComponentAttributeMatcher] Selected match ru.vyarus:gradle-use-python-plugin:2.3.0 configuration runtime from candidates [ru.vyarus:gradle-use-python-plugin:2.3.0 configuration runtime] for {}
12:17:00.088 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve files of :classpath' started
12:17:00.089 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Resolve files of :classpath'
12:17:00.089 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve files of :classpath' completed
12:17:00.093 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Apply plugin ru.vyarus.use-python to root project 'sample-project'' started
12:17:00.094 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Apply plugin ru.vyarus.use-python to root project 'sample-project''
12:17:00.094 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Apply plugin ru.vyarus.use-python to root project 'sample-project'' completed
12:17:00.095 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Apply script build.gradle to root project 'sample-project''
12:17:00.095 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Apply script build.gradle to root project 'sample-project'' completed
12:17:00.095 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 0.065 secs
12:17:00.095 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Configure project :'
12:17:00.095 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Configure project :' completed
12:17:00.095 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Configure build'
12:17:00.096 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Configure build' completed
12:17:00.098 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:17:00.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
12:17:00.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:17:00.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Where:
12:17:00.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Build file 'Documents/sample-project/build.gradle' line: 30
12:17:00.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:17:00.099 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
12:17:00.100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] An exception occurred applying plugin request [id: 'ru.vyarus.use-python', version: '2.3.0']
12:17:00.100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Failed to apply plugin [id 'ru.vyarus.use-python']
12:17:00.100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Could not find method register() for arguments [checkPython, class ru.vyarus.gradle.plugin.python.task.CheckPythonTask, ru.vyarus.gradle.plugin.python.PythonPlugin$_apply_closure2@1554760d] on task set of type org.gradle.api.internal.tasks.DefaultTaskContainer.
12:17:00.100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:17:00.100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
12:17:00.100 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
12:17:00.101 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:17:00.101 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
12:17:00.101 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
12:17:00.101 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 0s
12:17:00.101 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1 completed (0 worker(s) in use)
12:17:00.102 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 10: released lock on root.1
12:17:00.102 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Run build'
12:17:00.102 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Run build' completed
12:17:00.109 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
12:17:00.109 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
12:17:00.109 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.001 secs
12:17:00.146 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for Artifact transforms cache (.gradle/caches/transforms-1)
12:17:00.146 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on Artifact transforms cache (.gradle/caches/transforms-1).
12:17:00.147 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopping 0 deployment handles
12:17:00.147 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopped deployment handles
12:17:00.149 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for file hash cache (Documents//sample-project/.gradle/4.8.1/fileHashes)
12:17:00.151 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on file hash cache (Documents//sample-project/.gradle/4.8.1/fileHashes).
12:17:00.151 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Generated Gradle JARs cache (.gradle/caches/4.8.1/generated-gradle-jars) was closed 0 times.
12:17:00.152 [DEBUG] [org.gradle.cache.internal.DefaultPersistentDirectoryCache] VCS Checkout Cache (Documents//sample-project/.gradle/vcsWorkingDirs) has last been cleaned up 12 hours ago
12:17:00.152 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache VCS Checkout Cache (Documents//sample-project/.gradle/vcsWorkingDirs) was closed 0 times.
12:17:00.153 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for artifact cache (.gradle/caches/modules-2)
12:17:00.154 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-metadata.bin (.gradle/caches/modules-2/metadata-2.58/module-metadata.bin)
12:17:00.155 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-artifacts.bin (.gradle/caches/modules-2/metadata-2.58/module-artifacts.bin)
12:17:00.155 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-artifact.bin (.gradle/caches/modules-2/metadata-2.58/module-artifact.bin)
12:17:00.156 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on artifact cache (.gradle/caches/modules-2).
12:17:00.161 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
12:17:00.293 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientInputForwarder] Dispatching close input message: org.gradle.launcher.daemon.protocol.CloseInput@16a1de9a
12:17:00.293 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 14: dispatching class org.gradle.launcher.daemon.protocol.CloseInput
12:17:00.295 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Build file 'Documents//sample-project/build.gradle' line: 30
An exception occurred applying plugin request [id: 'ru.vyarus.use-python', version: '2.3.0']] from daemon DaemonInfo{pid=63457, address=[4b92e6ea-7e9e-4866-ad56-e7fff70f4911 port:58382, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1622702783683, context=DefaultDaemonContext[uid=d442c57a-8b93-47fd-b5ce-f8a411a7350b,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home,daemonRegistryDir=.gradle/daemon,pid=63457,idleTimeout=10800000,daemonOpts=-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=US-ASCII,-Duser.country=IN,-Duser.language=en,-Duser.variant]} (build should be done).
12:17:00.295 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
12:17:00.297 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop
`

**snippet from build.gradle**

```
plugins{
    id ("ru.vyarus.use-python") version "2.3.0"
}

python {
    pip("grafanalib==0.5.13")
    scope = VIRTUALENV
}
```

Gradle Version: 4.8.1

**Comment by xvik** [comment]
Version 2.3.0 requires [gradle 5](https://github.com/xvik/gradle-use-python-plugin#compatibility)
You should use [1.2.0](https://github.com/xvik/gradle-use-python-plugin/tree/1.2.0) for gradle 4

**Comment by amanjain08** [comment]
Thank you.
