### ISSUE TITLE
Kotlin rewrite

### ISSUE THREAD

**Issue by elect86** [xvik/gradle-use-python-plugin#21]
Hi,

I'm looking into some (maintained) tools to manage python from Gradle in order to easier project management for scientists and researchers and this project looks like my best bet.

However, I'd like to offer a DSL interface in order to simplify at maximum user interaction and Kotlin is the best in this regards. I can provide a PR if you are interested

**Comment by xvik** [comment]
Hi! 
Thank you for the proposition, but I don't like kotlin (its syntax). Besides, groovy is much more flexible than kotlin (there is a cost ofc., but fair enough when used properly).

Could you please share more details on what exactly you want to improve in the plugin?
If there are configuration issues related to kotlin gradle files, I'm sure there are ways to fix it without a complete rewrite.

**Comment by elect86** [comment]
I just wanted some statically typed language, in order to infer properly variables and so on with a potential DSL configuration.

But since you don't like it, there is no point

If I ever pick up enough interest and have enough time to invest, I'll ping you again
