### ISSUE TITLE
Support Pipfile as alternative to requirements.txt

### ISSUE THREAD

**Issue by aadrian** [xvik/gradle-use-python-plugin#76]
Please support **`Pipfile`** as alternative to the limited `requirements.txt`.

e.g. https://pipenv.pypa.io/en/latest/basics/#example-pipfile-pipfile-lock

Thank you.

**Comment by xvik** [comment]
This actually implies pipenv package support (because its lock file is useless without it). I will read about pipenv later to understand if it worth efforts.

**Comment by xvik** [comment]
[4.0.0 released](https://github.com/xvik/gradle-use-python-plugin/releases/tag/4.0.0) with venv support.

I looked what pipenv is and I really see no value in supporting it: this plugin suppose to use existing python modules for something. Raw pip abilities should be more than enouth for simple use-cases. And complex use-cases should be more related to python modules development, which is out of plugin scope.

I'm closing this now, but if someone would share a real use-case when potential pipenv usage (in context of plugin) would be hard to avoid requirement, I'll of course re-consider pipenv addition. Technically its not hard, but I just don't see a good reason.

So please reopen in case of real need (or open new issue).
