### ISSUE TITLE
Usage of deprecate API when using Gradle 6.2.1 (using release 2.1.0)

### ISSUE THREAD

**Issue by jakubhava** [xvik/gradle-use-python-plugin#9]
Type 'PipInstallTask': non-property method 'memoizedMethodPriv$getModulesToInstall()' should not be annotated with: @Internal

Thanks for great plugin!

**Comment by xvik** [comment]
Thank you! 
Gradle complains about some other methods too: these methods are synthetic (created by `@Memoized` annotation with "incorrectly" inherited `@Internal`). I did not find a quick solution during the last release, but I will look to work around it somehow.

**Comment by jakubhava** [comment]
Thank you @xvik!
